---
apiVersion: v1
kind: ConfigMap
metadata:
  name: truenas-config
  namespace: flux-system
data:
  TRUENAS_HOST: "192.168.20.106"
  TRUENAS_PROTOCOL: "https"
  TRUENAS_PORT: "443"
  TRUENAS_USERNAME: "truenas_admin"
  TRUENAS_ISCSI_PORTAL: "192.168.20.106:3260"
  DATASET_PARENT: "home-share/iscsi/k8s/prod/volumes"
  DATASET_SNAPSHOTS: "home-share/iscsi/k8s/prod/snapshots"
  STORAGE_CLASS_NAME: "iscsi"
  ALLOW_INSECURE: "true"
