storageClasses:
    - name: ENC[AES256_GCM,data:itescF8=,iv:sslh/W3wmfCEtvwCel9CaG567+xgYuRsirgyNDCcvL4=,tag:w/bS9xlMzEysHZsq+h8XRA==,type:str]
      defaultClass: ENC[AES256_GCM,data:/AES0Q==,iv:Xt2JbI0Vn7y//Vhwu0pGA3jKa5Kv8srF5htOA2vjUJo=,tag:cGjqNCpzKIVkDqFeXef1Ow==,type:bool]
      reclaimPolicy: ENC[AES256_GCM,data:tibO0EiI,iv:PcspXn7AiQAqKPELtYMekFqMRWUR4FooxLdBiLWRncI=,tag:G4PgvFBJhRsFhirFf72tbQ==,type:str]
      volumeBindingMode: ENC[AES256_GCM,data:0013FK8HXzme,iv:sx8AbX0pYO7FipBqUKu1GpfS2hExfKM6tMHwW5YRY2k=,tag:SuS+bxPpZ1N/JQHVubbkbA==,type:str]
      allowVolumeExpansion: ENC[AES256_GCM,data:vtrgyg==,iv:JvJaI2PmeTmhl3iA+Ysm7x5rOPkf9lHdsrcjC33OKLg=,tag:Fwu0PWrLhfNBHLs/MKoXNQ==,type:bool]
      parameters:
        fsType: ENC[AES256_GCM,data:5dw0Kw==,iv:5mM/MaoqhcC+ukYY413ZHu1ywgGw4vi83fhYhEPxQ6U=,tag:hq5MiD9YbmdnAAD/HXkN7w==,type:str]
        detachedVolumesFromSnapshots: ENC[AES256_GCM,data:/Jye7zY=,iv:0XuxW6AlxYliCFI02qoTUbVMefmEE7ePEkIcaedM2GY=,tag:AROOtcwN9rCbMNLJUloyEA==,type:str]
driver:
    config:
        driver: ENC[AES256_GCM,data:MN/lu67ImerAR3j4ngv0Zlk=,iv:f2FTUsRs7agyVcBJRaLDK5dc9m7+x3L+YZV7Pc77gzU=,tag:8JZN325QUnT54Zy3aFn0fA==,type:str]
        instance_id: null
        httpConnection:
            protocol: ENC[AES256_GCM,data:hi/M3/E=,iv:DCMbovU3+tysW+Y2ZfJ0/EkeoVnI3F1EUFzIaLCptxo=,tag:pNX5+kq2aTfyun2Zupm0ew==,type:str]
            host: ENC[AES256_GCM,data:vAtEsk3quCwromjkkAw=,iv:HfufDSelnyjeMA9cOtSPvazz2ua+SoDCFe3OOhV/Kcw=,tag:1kTurlhD6jXP3jAez/5ECA==,type:str]
            port: ENC[AES256_GCM,data:AH1T,iv:8WTZqPunHipMdLyYFW8tpkjSe33nT0A2/zhBClJ6ITc=,tag:iMr14LuueAX2dmtPqyCUiA==,type:int]
            username: ENC[AES256_GCM,data:cseA0mVNSaCC,iv:3zBEWDBkCqBvtHewmT9WBvW38IDI5yO8yE6a1joIbko=,tag:7imYALkYz+CjyF7cvsDXrQ==,type:str]
            password: ENC[AES256_GCM,data:dMxg9kP0lzDWm7otqBM13vZorg==,iv:HehCVeF0kOrmKHdVN73jghhIND17FarmA4ocuXpRjKY=,tag:M2kXlKntfAZ4c7AENSaTwQ==,type:str]
            allowInsecure: ENC[AES256_GCM,data:Ghdw9Q==,iv:IEEHovZve/2SS14eAa4PBaue75ksd+XAWHCc3OgQkFs=,tag:bFoigB+iG4jeCeFlCmrjng==,type:bool]
        zfs:
            datasetParentName: ENC[AES256_GCM,data:GVpzbS0x0Vv1VBtFLt8mgmxKfbcwKR2A16xYMWthLX8=,iv:iBLPhIaLiKYxUYMuY2xPufzpdcaxo6OqNOXjFwzPSok=,tag:bhhIZm5gfUXy/r4Uf7krQA==,type:str]
            detachedSnapshotsDatasetParentName: ENC[AES256_GCM,data:sRhj6yvQFWsR2b0nT529J+CrUnndkr02xN7ZVe5hvH7SNA==,iv:k0rxtxXunG9rVrDJKF4BPQlA5ROiC90Ozu99n+vF+YM=,tag:dLafNgchEudL11fPnpZBjw==,type:str]
            zvolCompression: ENC[AES256_GCM,data:VwE=,iv:Ho5GmDm/O73CyM463+ll0H7bVe+6Zpr9VzdbWqYa1iU=,tag:nu0NaqCJGcOXhJa4lfeKsA==,type:str]
            zvolDedup: null
            zvolEnableReservation: ENC[AES256_GCM,data:bQ+BaN0=,iv:/rPsoALAJ7uWAa1JFHJZSLm2PY5ujCguYP+PmmQhcb4=,tag:TQ1IQNl16ultXj24o7298A==,type:bool]
            zvolBlocksize: null
        iscsi:
            targetPortal: ENC[AES256_GCM,data:qaKNKoGfwdIvP2VzQbySyuU8aA==,iv:1ymc0gQSX75bU7GokMiop8wclXe+PbtI5rLW7NvAEhc=,tag:W5OmTjESeuuVtAkKGXrlUA==,type:str]
            interface: null
            namePrefix: ENC[AES256_GCM,data:EdRMlA==,iv:eWyFbRr++zejhf1yKQSHF4pu/LkKxIxbcGcNiHm8zO8=,tag:9GgPwiJRoIk1bJgZZCkXXA==,type:str]
            nameSuffix: ENC[AES256_GCM,data:ZzZOq/FnZA==,iv:VGCVGr/cN8BlRzmF6n4Sg9M0yLuLIMAx0ZFGmwjuOq4=,tag:oWfDubycVdE8/bKCYC8Msw==,type:str]
            targetGroups:
                - targetGroupPortalGroup: ENC[AES256_GCM,data:9Q==,iv:/LkGxhgtlF6fmyXavKaHB0Kn8H1bleCae0MWYHSXutw=,tag:r4u9BWxNQFZhKBW9EA6LSA==,type:int]
                  targetGroupInitiatorGroup: ENC[AES256_GCM,data:1w==,iv:Zg0SnS9EUTxHIA13r7evfKHVpO0BaFcuz0RfGtDzpxY=,tag:Yu8UWBCZ2C2vn6W5Ws1OOw==,type:int]
                  targetGroupAuthType: ENC[AES256_GCM,data:9f4vQg==,iv:RA8ZYogSyP9ab9jc3zZ3NIfZBtABIorUq9L8XJgvzuE=,tag:5msjhXAY/MzbjNsi2mwJnA==,type:str]
                  targetGroupAuthGroup: null
            extentInsecureTpc: ENC[AES256_GCM,data:/KmvYw==,iv:As9/xq2cp+gMxlqBUJeLpUxy87S3qJlgLFlo6W8lR2M=,tag:nLLrXOditaMmYFPt4aJ7+A==,type:bool]
            extentXenCompat: ENC[AES256_GCM,data:+MIsZvs=,iv:GuhdUea2Nv7uHbIzztrasgB6hGJ13OAcKxcvv6wd7fE=,tag:+uU17XMBnbwp/ojI9muIMA==,type:bool]
            extentDisablePhysicalBlocksize: ENC[AES256_GCM,data:PupFGA==,iv:nhzcmnpmgChLia3BpSeTOCrrGJcrwlfqiNcY1nlb8UM=,tag:YSQcw63Kpg1i9/8e+OIywQ==,type:bool]
            extentBlocksize: ENC[AES256_GCM,data:Wznq,iv:dAhTEOBAmRVeZkllfdV6VIvXJqPbFzuzA/MjUViqVWw=,tag:vVsYI0cIbXUdmHFkuae1rw==,type:int]
            extentRpm: ENC[AES256_GCM,data:ZgZV,iv:gsqaPRCHm4834WrO+V/HavsHYsda4GISMysoAvFqxJk=,tag:WW0wSjT8SUQ18do+UBed9A==,type:str]
            extentAvailThreshold: ENC[AES256_GCM,data:RQ==,iv:0WXh5xVudMPl0OK+y0fmo/SnNWI/zELkydSKbHPpPiM=,tag:Fm6eepRK5NFjV76NzCpOWw==,type:int]
sops:
    age:
        - recipient: age1vml3vk5uzyztj96qgz7n0a6w8ynvtmxfarkp0jdl0hvcj003895qcp6z09
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UUk1VXh5UkVmVlhVeGts
            cnp3empPWXFMakxRaHhXdW1jUkZaTUM4Q2xJCjdPK29EQmNlVUFqOHo0aWp3WSty
            UFEva0lEbWFFR0hUNURWTHZ2QmJ0RVEKLS0tIFRoT1BZMW1yaTFXeUdoa3liYVI1
            MWNhaWY1SmZ3N3N0RWhBcGwxUHhHWWsKLK5hVq6yce/9szjxaFTBThOUdLHXZTJb
            uBrcgLBaz55xO0R4kUmYQ/t43SA4oe7DQu/xbigJdXv2iiyiSxqEAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T02:08:30Z"
    mac: ENC[AES256_GCM,data:ujnUBkGYopyF9QPvSa630gNLJ+iChFNFWaN6+cSOsvC3MZi7ExyB1XnVvXXb/UHdb9rnreqfjljRMIrDlk6onZVY2RcuWWJqmTHYbrkDqaRNXkLUO2fhGBXm1jYx8tv7orgHg1fmeG6vpEA5OfKhbKvw8vdvOPORUvnU53LZRfE=,iv:HB9ZjTTTW8YxXy6lV1ZHoCz/GFqZgczTv+uTPsErsus=,tag:mSy6RFnefECSHLubhMFzdg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
