---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - configmap.yaml
  - secrets.enc.yaml
  - helmrelease.yaml
postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: truenas-config
      - kind: Secret
        name: truenas-credentials
