apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
secretGenerator:
  - name: csi-values
    files:
      - values.yaml=csi-values.enc.yaml
configurations:
  - kustomizeconfig.yaml
