apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sop.yaml
  - configmap.sops.yaml
  - deployment.yaml
  - service.yaml
  - pv.yaml
  - pvc.yaml
  - ingress.yaml
 # - gateway.yaml
