apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-cd.yaml
  - bjw-s.yaml
  - cnpg.yaml
  - democratic-csi-local-path.yaml
  - democratic-csi-smb.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - firefly.yaml
  - homepage.yaml
  - jetstack.yaml
  - kube-prometheus-stack.yaml
  - kyverno.yaml
  - longhorn.yaml
  - mariadb-operator.yaml
  - onepassword.yaml
  - ot-heml.yaml
  - renovate.yaml
  - tailscale.yaml
