apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/external-secrets
  - ../base/onepassword-connect
  - ../base/tailscale
  - ../base/kyverno
  - ../base/cloudnativepg
 # - redis-operator
#  - ../base/local-path
  - longhorn
  #  - ../base/csi-driver-smb
